### ISSUE TITLE
FR: Get both active and inactive tasks in one function call

### ISSUE THREAD

**Issue by krlmlr** [psolymos/clickrup#11]
via `cu_get_tasks(archived = NA)` .

**Comment by psolymos** [comment]
This seems doable by concatenating results from 2 calls into the `$tasks` element. However:

- need to add paging, there might be multiple calls needed to get all tasks from a list
- same goes for archived

Should there be a `.concat()` function to merge similar objects and adjust class attribute (remove it from parts and add it once to return object)?

**Comment by krlmlr** [comment]
Yes, paging makes it much more difficult. For now it's easier to work around for the caller.
